name: py3_course
channels:
  - conda-forge
dependencies:
  - python=3
  - basemap
  - bokeh=1.1.0
  - cartopy
  - cf_units
  - cmocean
  - dask-image=0.2.0
  - dask-ml=0.13.0
  - dask=1.2
  - gsw
  - haversine
  - hdf5
  - matplotlib<3
  - nbserverproxy
  - netCDF4
  - nodejs=8.9
  - nomkl
  - notebook<5.7.5
  - numba
  - numpy
  - pandas
  - pip
  - py-xgboost
  - pyarrow==0.12.0
  - python-graphviz
  - requests
  - scipy
  - seaborn
  - seawater
  - tornado=5
  - xarray
  - pip:
    - dask_xgboost
    - mimesis
    - jupyterlab==1.0.0a8
    - dask-labextension==0.4.0a1
